name: module3_task0
on:
  push:
  schedule:
    - cron: "0 21 * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make help
